# Generated by Django 3.1.2 on 2021-03-26 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210326_1735'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='contact',
        #     name='date',
        #     field=models.DateField(default=datetime.datetime(2021, 3, 26, 17, 45, 44, 666742)),
        # ),
    ]
