# Generated by Django 3.1.2 on 2021-03-26 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210326_1745'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='contact',
        #     name='date',
        # ),
    ]
