# Generated by Django 4.0.4 on 2022-07-05 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_destination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Address2',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='CollegeName',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='JeeAppNo',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='JeePercentile',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='JeeRank',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='MhtcetRank',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Percentage',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='file',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='file1',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone1',
        ),
    ]
