# Generated by Django 4.0.4 on 2022-07-05 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_contact_address2_remove_contact_collegename_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='Aadhar',
        ),
    ]
