# Generated by Django 4.0.4 on 2022-07-05 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_contact_aadhar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='MhtcetAppNo',
            new_name='ApplicationNumber',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='MhtcetPercentile',
            new_name='Percentile',
        ),
    ]
