# Generated by Django 4.0.4 on 2022-07-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_rename_mhtcetappno_contact_applicationnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='file',
            field=models.FileField(default='', upload_to=''),
        ),
        migrations.AddField(
            model_name='contact',
            name='file1',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
